[project]
name = "le_projet_a_moi"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pymodbus>=3.11.2",
]

[dependency-groups]
dev = []
